language: node_js
node_js:
  - "8.1.2"

branches:
  only:
    - master

before_script:
  - npm i -g firebase-tools

script:
  - npm run build

after_success:
  - firebase deploy --token $TOKEN --non-interactive

nitifications:
  email:
    on_failure: change
    on_success: change