language: node_js
node_js:
  - "6.11.2"

branches:
  only:
    - master

before_script:
  - npm i -g firebase-tools

script:
  - npm rebuild node-sass --force
  - npm run build
n
after_success:
  - firebase deploy --token $TOKEN --non-interactive

nitifications:
  email:
    on_failure: change
    on_success: change